# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170504_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='작성자명', max_length=20),
            preserve_default=False,
        ),
    ]
